### ISSUE TITLE
Don't use mattetti/audio/riff

### ISSUE THREAD

**Issue by mattetti** [go-audio/wav#1]
This package should be standalone and doesn't need to rely on a different package.

**Comment by glaslos** [comment]
How about moving riff into the go-audio org? It could also be merged into go-audio/wav but there might be arguments to keep it separate (e.g. other formats using RIFF like RIFF MIDI).

**Comment by mattetti** [comment]
I think that's a good idea

**Comment by glaslos** [comment]
Unfortunately that's here you have to take over :)

**Comment by mattetti** [comment]
Still planning on moving the package, didn't get to it yet, but it's going to happen :)

**Comment by mattetti** [comment]
finally done it and now with go modules support
