### ISSUE TITLE
Can I encode g729 wav file?

### ISSUE THREAD

**Issue by aaerofeev** [go-audio/wav#13]
I try encode g729 codec wav file, and get panic: could not get sample decode func unhandled byte depth:0
Can I encode file from this codec with go-audio/wav?

**Comment by mattetti** [comment]
Unfortunately G.729 doesn't use wav format so it isn't supported:  https://en.wikipedia.org/wiki/G.729
However, if you're interested in adding support, I'd be glad to give you pointers
