### ISSUE TITLE
Please use standard io.EOF to represent end of file events

### ISSUE THREAD

**Issue by mcandre** [go-audio/wav#24]
It's risky for applications to handle errors based on string matching (e.g. `error reading chunk header - EOF`). Instead, it would be better to return `io.EOF` when a WAV read stream is finished.

**Comment by mcandre** [comment]
Apologies, I am navigating the docs without the good fortune of an example application. I now see that I should attempt to `Read()` chunks, and then will receive any `io.EOF`s.

**Comment by mattetti** [comment]
There are a few examples such as https://github.com/go-audio/wav/blob/master/cmd/wavtoaiff/main.go https://github.com/go-audio/generator/blob/master/examples/offline/main.go

But I agree documentation could be better.
